flaskblog/main/routes.py
from flask import Blueprint, request, render_template

from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskblog/templates/includes/_navbar.html
<header class="site-header">

    <nav class="navbar navbar-expand-lg navbar-dark bg-steel">
        <div class="container">
            <a class="navbar-brand" href="#">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/login" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="/register" class="nav-link">Register</a>
                    </li>
                </ul>
                {#                <form class="form-inline my-2 my-lg-0">#}
                {#                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
                {#                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
                {#                </form>#}
            </div>
        </div>
    </nav>

</header>